<div id="adminBar" class="clearfix">
  <div class="button">
    <a href="index.php?page=admin&admin=addGame">Add Game</a>
  </div>

  <div class="button">
    <a href="index.php?page=admin&admin=editGame">Edit Game</a>
  </div>

  <div class="button">
    <a href="index.php?page=admin&admin=addCreator">Add Creator</a>
  </div>

  <div class="button">
    <a href="index.php?page=admin&admin=editCreator">Edit Creator</a>
  </div>

  <div class="button">
    <a href="index.php?page=admin&admin=addPlatform">Add Platform</a>
  </div>

  <div class="button">
    <a href="index.php?page=admin&admin=addGenre">Add Genre</a>
  </div>
</div>
