<div id="adminBar" class="clearfix">
  <div class="button">
    <a href="admin/addGame.php">Add Game</a>
  </div>

  <div class="button">
    <a href="admin/editGame.php">Edit Game</a>
  </div>

  <div class="button">
    <a href="admin/addCreator.php">Add Creator</a>
  </div>

  <div class="button">
    <a href="admin/editCreator.php">Edit Creator</a>
  </div>

  <div class="button">
    <a href="admin/addPlatform.php">Add Platform</a>
  </div>

  <div class="button">
    <a href="admin/addGenre.php">Add Genre</a>
  </div>
</div>
