<div id="adminBar" class="clearfix">
  <div class="button">
    <a href="addGame.php">Add Game</a>
  </div>

  <div class="button">
    <a href="editGame.php">Edit Game</a>
  </div>

  <div class="button">
    <a href="addCreator.php">Add Creator</a>
  </div>

  <div class="button">
    <a href="editCreator.php">Edit Creator</a>
  </div>

  <div class="button">
    <a href="addPlatform.php">Add Platform</a>
  </div>

  <div class="button">
    <a href="addGenre.php">Add Genre</a>
  </div>
</div>
